url: "https://api.github.com/repos/NeonGamerBot-QK/cat/pulls/2"
id: 1394594923
node_id: "PR_kwDOJR2jEM5TH9Rr"
html_url: "https://github.com/NeonGamerBot-QK/cat/pull/2"
diff_url: "https://github.com/NeonGamerBot-QK/cat/pull/2.diff"
patch_url: "https://github.com/NeonGamerBot-QK/cat/pull/2.patch"
issue_url: "https://api.github.com/repos/NeonGamerBot-QK/cat/issues/2"
number: 2
state: "open"
locked: false
title: "Patch1"
user: {
  "login": "NeonGamerBot-QK",
  "id": 58448036,
  "node_id": "MDQ6VXNlcjU4NDQ4MDM2",
  "avatar_url": "https://avatars.githubusercontent.com/u/58448036?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/NeonGamerBot-QK",
  "html_url": "https://github.com/NeonGamerBot-QK",
  "followers_url": "https://api.github.com/users/NeonGamerBot-QK/followers",
  "following_url": "https://api.github.com/users/NeonGamerBot-QK/following{/other_user}",
  "gists_url": "https://api.github.com/users/NeonGamerBot-QK/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/NeonGamerBot-QK/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/NeonGamerBot-QK/subscriptions",
  "organizations_url": "https://api.github.com/users/NeonGamerBot-QK/orgs",
  "repos_url": "https://api.github.com/users/NeonGamerBot-QK/repos",
  "events_url": "https://api.github.com/users/NeonGamerBot-QK/events{/privacy}",
  "received_events_url": "https://api.github.com/users/NeonGamerBot-QK/received_events",
  "type": "User",
  "site_admin": false
}
body: null
created_at: "2023-06-15T18:36:46Z"
updated_at: "2023-06-15T18:36:46Z"
closed_at: null
merged_at: null
merge_commit_sha: null
assignee: null
assignees: []
requested_reviewers: []
requested_teams: []
labels: []
milestone: null
draft: false
commits_url: "https://api.github.com/repos/NeonGamerBot-QK/cat/pulls/2/commits"
review_comments_url: "https://api.github.com/repos/NeonGamerBot-QK/cat/pulls/2/comments"
review_comment_url: "https://api.github.com/repos/NeonGamerBot-QK/cat/pulls/comments{/number}"
comments_url: "https://api.github.com/repos/NeonGamerBot-QK/cat/issues/2/comments"
statuses_url: "https://api.github.com/repos/NeonGamerBot-QK/cat/statuses/3155cc35f0ffb1309d1c2c7dab5e552b4cc8f836"
head: {
  "label": "NeonGamerBot-QK:patch1",
  "ref": "patch1",
  "sha": "3155cc35f0ffb1309d1c2c7dab5e552b4cc8f836",
  "user": {
    "login": "NeonGamerBot-QK",
    "id": 58448036,
    "node_id": "MDQ6VXNlcjU4NDQ4MDM2",
    "avatar_url": "https://avatars.githubusercontent.com/u/58448036?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/NeonGamerBot-QK",
    "html_url": "https://github.com/NeonGamerBot-QK",
    "followers_url": "https://api.github.com/users/NeonGamerBot-QK/followers",
    "following_url": "https://api.github.com/users/NeonGamerBot-QK/following{/other_user}",
    "gists_url": "https://api.github.com/users/NeonGamerBot-QK/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/NeonGamerBot-QK/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/NeonGamerBot-QK/subscriptions",
    "organizations_url": "https://api.github.com/users/NeonGamerBot-QK/orgs",
    "repos_url": "https://api.github.com/users/NeonGamerBot-QK/repos",
    "events_url": "https://api.github.com/users/NeonGamerBot-QK/events{/privacy}",
    "received_events_url": "https://api.github.com/users/NeonGamerBot-QK/received_events",
    "type": "User",
    "site_admin": false
  },
  "repo": {
    "id": 622699280,
    "node_id": "R_kgDOJR2jEA",
    "name": "cat",
    "full_name": "NeonGamerBot-QK/cat",
    "private": false,
    "owner": {
      "login": "NeonGamerBot-QK",
      "id": 58448036,
      "node_id": "MDQ6VXNlcjU4NDQ4MDM2",
      "avatar_url": "https://avatars.githubusercontent.com/u/58448036?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/NeonGamerBot-QK",
      "html_url": "https://github.com/NeonGamerBot-QK",
      "followers_url": "https://api.github.com/users/NeonGamerBot-QK/followers",
      "following_url": "https://api.github.com/users/NeonGamerBot-QK/following{/other_user}",
      "gists_url": "https://api.github.com/users/NeonGamerBot-QK/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/NeonGamerBot-QK/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/NeonGamerBot-QK/subscriptions",
      "organizations_url": "https://api.github.com/users/NeonGamerBot-QK/orgs",
      "repos_url": "https://api.github.com/users/NeonGamerBot-QK/repos",
      "events_url": "https://api.github.com/users/NeonGamerBot-QK/events{/privacy}",
      "received_events_url": "https://api.github.com/users/NeonGamerBot-QK/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/NeonGamerBot-QK/cat",
    "description": "Random images of cats",
    "fork": false,
    "url": "https://api.github.com/repos/NeonGamerBot-QK/cat",
    "forks_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/forks",
    "keys_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/teams",
    "hooks_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/hooks",
    "issue_events_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/issues/events{/number}",
    "events_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/events",
    "assignees_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/assignees{/user}",
    "branches_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/branches{/branch}",
    "tags_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/tags",
    "blobs_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/languages",
    "stargazers_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/stargazers",
    "contributors_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/contributors",
    "subscribers_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/subscribers",
    "subscription_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/subscription",
    "commits_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/contents/{+path}",
    "compare_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/merges",
    "archive_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/downloads",
    "issues_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/issues{/number}",
    "pulls_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/labels{/name}",
    "releases_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/releases{/id}",
    "deployments_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/deployments",
    "created_at": "2023-04-02T21:30:32Z",
    "updated_at": "2023-04-19T00:53:11Z",
    "pushed_at": "2023-06-15T18:36:46Z",
    "git_url": "git://github.com/NeonGamerBot-QK/cat.git",
    "ssh_url": "git@github.com:NeonGamerBot-QK/cat.git",
    "clone_url": "https://github.com/NeonGamerBot-QK/cat.git",
    "svn_url": "https://github.com/NeonGamerBot-QK/cat",
    "homepage": "https://saahild.com/cat",
    "size": 338,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "react"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 1,
    "watchers": 0,
    "default_branch": "master",
    "allow_squash_merge": true,
    "allow_merge_commit": true,
    "allow_rebase_merge": true,
    "allow_auto_merge": false,
    "delete_branch_on_merge": false,
    "allow_update_branch": false,
    "use_squash_pr_title_as_default": false,
    "squash_merge_commit_message": "COMMIT_MESSAGES",
    "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
    "merge_commit_message": "PR_TITLE",
    "merge_commit_title": "MERGE_MESSAGE"
  }
}
base: {
  "label": "NeonGamerBot-QK:master",
  "ref": "master",
  "sha": "f01af22f8f4f3aa3e14724ff318d711a05cbf4f3",
  "user": {
    "login": "NeonGamerBot-QK",
    "id": 58448036,
    "node_id": "MDQ6VXNlcjU4NDQ4MDM2",
    "avatar_url": "https://avatars.githubusercontent.com/u/58448036?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/NeonGamerBot-QK",
    "html_url": "https://github.com/NeonGamerBot-QK",
    "followers_url": "https://api.github.com/users/NeonGamerBot-QK/followers",
    "following_url": "https://api.github.com/users/NeonGamerBot-QK/following{/other_user}",
    "gists_url": "https://api.github.com/users/NeonGamerBot-QK/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/NeonGamerBot-QK/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/NeonGamerBot-QK/subscriptions",
    "organizations_url": "https://api.github.com/users/NeonGamerBot-QK/orgs",
    "repos_url": "https://api.github.com/users/NeonGamerBot-QK/repos",
    "events_url": "https://api.github.com/users/NeonGamerBot-QK/events{/privacy}",
    "received_events_url": "https://api.github.com/users/NeonGamerBot-QK/received_events",
    "type": "User",
    "site_admin": false
  },
  "repo": {
    "id": 622699280,
    "node_id": "R_kgDOJR2jEA",
    "name": "cat",
    "full_name": "NeonGamerBot-QK/cat",
    "private": false,
    "owner": {
      "login": "NeonGamerBot-QK",
      "id": 58448036,
      "node_id": "MDQ6VXNlcjU4NDQ4MDM2",
      "avatar_url": "https://avatars.githubusercontent.com/u/58448036?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/NeonGamerBot-QK",
      "html_url": "https://github.com/NeonGamerBot-QK",
      "followers_url": "https://api.github.com/users/NeonGamerBot-QK/followers",
      "following_url": "https://api.github.com/users/NeonGamerBot-QK/following{/other_user}",
      "gists_url": "https://api.github.com/users/NeonGamerBot-QK/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/NeonGamerBot-QK/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/NeonGamerBot-QK/subscriptions",
      "organizations_url": "https://api.github.com/users/NeonGamerBot-QK/orgs",
      "repos_url": "https://api.github.com/users/NeonGamerBot-QK/repos",
      "events_url": "https://api.github.com/users/NeonGamerBot-QK/events{/privacy}",
      "received_events_url": "https://api.github.com/users/NeonGamerBot-QK/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/NeonGamerBot-QK/cat",
    "description": "Random images of cats",
    "fork": false,
    "url": "https://api.github.com/repos/NeonGamerBot-QK/cat",
    "forks_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/forks",
    "keys_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/teams",
    "hooks_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/hooks",
    "issue_events_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/issues/events{/number}",
    "events_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/events",
    "assignees_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/assignees{/user}",
    "branches_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/branches{/branch}",
    "tags_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/tags",
    "blobs_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/languages",
    "stargazers_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/stargazers",
    "contributors_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/contributors",
    "subscribers_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/subscribers",
    "subscription_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/subscription",
    "commits_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/contents/{+path}",
    "compare_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/merges",
    "archive_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/downloads",
    "issues_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/issues{/number}",
    "pulls_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/labels{/name}",
    "releases_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/releases{/id}",
    "deployments_url": "https://api.github.com/repos/NeonGamerBot-QK/cat/deployments",
    "created_at": "2023-04-02T21:30:32Z",
    "updated_at": "2023-04-19T00:53:11Z",
    "pushed_at": "2023-06-15T18:36:46Z",
    "git_url": "git://github.com/NeonGamerBot-QK/cat.git",
    "ssh_url": "git@github.com:NeonGamerBot-QK/cat.git",
    "clone_url": "https://github.com/NeonGamerBot-QK/cat.git",
    "svn_url": "https://github.com/NeonGamerBot-QK/cat",
    "homepage": "https://saahild.com/cat",
    "size": 338,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "react"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 1,
    "watchers": 0,
    "default_branch": "master",
    "allow_squash_merge": true,
    "allow_merge_commit": true,
    "allow_rebase_merge": true,
    "allow_auto_merge": false,
    "delete_branch_on_merge": false,
    "allow_update_branch": false,
    "use_squash_pr_title_as_default": false,
    "squash_merge_commit_message": "COMMIT_MESSAGES",
    "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
    "merge_commit_message": "PR_TITLE",
    "merge_commit_title": "MERGE_MESSAGE"
  }
}
_links: {
  "self": {
    "href": "https://api.github.com/repos/NeonGamerBot-QK/cat/pulls/2"
  },
  "html": {
    "href": "https://github.com/NeonGamerBot-QK/cat/pull/2"
  },
  "issue": {
    "href": "https://api.github.com/repos/NeonGamerBot-QK/cat/issues/2"
  },
  "comments": {
    "href": "https://api.github.com/repos/NeonGamerBot-QK/cat/issues/2/comments"
  },
  "review_comments": {
    "href": "https://api.github.com/repos/NeonGamerBot-QK/cat/pulls/2/comments"
  },
  "review_comment": {
    "href": "https://api.github.com/repos/NeonGamerBot-QK/cat/pulls/comments{/number}"
  },
  "commits": {
    "href": "https://api.github.com/repos/NeonGamerBot-QK/cat/pulls/2/commits"
  },
  "statuses": {
    "href": "https://api.github.com/repos/NeonGamerBot-QK/cat/statuses/3155cc35f0ffb1309d1c2c7dab5e552b4cc8f836"
  }
}
author_association: "OWNER"
auto_merge: null
active_lock_reason: null
merged: false
mergeable: null
rebaseable: null
mergeable_state: "unknown"
merged_by: null
comments: 0
review_comments: 0
maintainer_can_modify: false
commits: 2
additions: 6
deletions: 2
changed_files: 2